name: Moodle Plugin CI
on:
  push:
    branches:
      - master


jobs:
   

   test_php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4]
        moodle-version: ["MOODLE_401_STABLE"]
        plugin-repo: ["https://github.com/Lysa14/moodle-local_cnw_smartcohort.git"]
        plugin-name: ["cnw_smartcohort"]
        node-version: [14]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}


     
      - name: Install Web Server (Apache)
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
     

      
      - name: Download Moodle
        run: |
          mkdir moodle
          wget https://github.com/moodle/moodle/archive/${{ matrix.moodle-version }}.zip
          unzip ${{ matrix.moodle-version }}.zip
          mv moodle-${{ matrix.moodle-version }}  moodle

      - name: Install Moodle Plugin 
        run: |
          cd  moodle/moodle-${{ matrix.moodle-version }}/local
          git clone ${{ matrix.plugin-repo }} 
          cd ../../..
          

      - name: Install PHP and Extensions
        run: |
          sudo apt-get install -y php8.2 php8.2-cli php8.2-xml php8.2-simplexml php8.2-dom php8.2-curl php8.2-zip php8.2-gd
          sudo systemctl restart apache2
     
      - name: Restart Apach
        run : sudo systemctl restart apache2

      - name: Install Composer Dependencies
        run: |
          cd  moodle/moodle-${{ matrix.moodle-version }}/
          composer install --prefer-dist --no-progress --no-suggest
          export PATH=$PATH:./vendor/bin   

      - name: Install Composer
        run: |
              mkdir -p bin
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php composer-setup.php --install-dir=bin --filename=composer
              php -r "unlink('composer-setup.php');"
    
      - name: Install PHPUnit
        run: |
          sudo apt-get install -y wget
          wget https://phar.phpunit.de/phpunit-9.5.28.phar
          chmod +x phpunit-9.5.28.phar
          sudo mv phpunit-9.5.28.phar /usr/local/bin/phpunit
  
      - name: Run PHPUnit Tests
        run: |
          cd moodle/moodle-${{ matrix.moodle-version }}/local
          ls -R
          phpunit moodle-local_${{ matrix.plugin-name }}/tests/. > resultat_tests.log

      - name: Upload Test Logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: |
            moodle/moodle-${{ matrix.moodle-version }}/local/resultat_tests.log

 
           
      - name: Run Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions:5.7.7
        with: 
          relative_dir:  ${{github.workspace}}/bin
    


   send_email_notification:
      runs-on: ubuntu-latest
      needs: test_php
      if: ${{ needs.test_php.result == 'success' }}
      steps:
        - name: Send Email
          if: always()
          uses: hilarion5/send-mail@v1
          with:
            smtp-server: ${{ secrets.SMTP_NAME }}
            smtp-port: 2525
            smtp-secure: false
            from-email: ${{ secrets.FROM_EMAIL }}
            to-email: ${{ secrets.SMTP_TO_EMAIL }}
            username: ${{ secrets.SMTP_USERNAME }}
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: Workflows Status Notifications
            body: |
              
              The build was ${{ needs.test_php.result }}.
              ----------------------------------------------
              Une nouvelle version de notre projet est disponible. Vous pouvez consulter la source du projet ici : https://github.com/${{ github.repository }}
              ---------------------------------------------
