name: PHP & MOODLE ci
on:
    push:
        branches:
            - master

jobs:
    security:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Install dependencies
            run: composer install --no-dev --optimize-autoloader

          - name: Run static code analysis
            run: phpstan analyze --no-progress --error-format=json | jq -r 'select(.message | startswith("Security issue"))'

          - name: Run dependency vulnerability check
            run: |
                wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.4.0-release.zip
                unzip dependency-check-5.4.0-release.zip
                ./dependency-check/bin/dependency-check.sh --project "php-moodle" --scan ${{github.workspace}} --format HTML -f "dependency-check-report.html"

